server:
  port: 9000
spring:
  application:
    name: nacos-discovery-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: nacos-discovery-provider
          uri: lb://nacos-discovery-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1